### ISSUE TITLE
Plot matrix of values inside maze visualization

### ISSUE THREAD

**Issue by afspies** [AISC-understanding-search/maze-transformer#108]
As a next step, I will make coloring nodes with attention matrix available. Should this be done in a new issue? If not, leave this PR open.

_Originally posted by @canrager in https://github.com/AISC-understanding-search/maze-transformer/issues/87#issuecomment-1479898587_

**Comment by canrager** [comment]
Implemented colorbar plotting without normalization. The colorbar's lower bound is fixed to 0 while the upper bound is adaptive to max node value passed. Thought this may be more intiuitive. If desired, node values have to be normalized before passing to MazePlot.

- [x] Walls are fixed to black color
- [x] Colorbar adaptive to node values

<img width="559" alt="Screenshot 2023-03-28 at 14 52 54" src="https://user-images.githubusercontent.com/61095597/228260405-d5da946a-3cd9-4466-a277-062a01803e95.png">
