### ISSUE TITLE
Add HookedTransformer and Config fixtures to integration tests

### ISSUE THREAD

**Issue by luciaquirke** [AISC-understanding-search/maze-transformer#119]
This will increase in priority when our tests become too slow.

As pointed out by Alex: https://github.com/AISC-understanding-search/maze-transformer/pull/81#issuecomment-1472437714

HookedTransformer and Config are slow to initialise so we want to add them to fixtures in `conftest.py` then use the fixtures in multiple tests. Then we have two options to avoid multiple initialisations:

1. We can scope the fixture to reset after every module rather than after every test. This is fine if the fixture objects are read only (Config seems like it would be read-only?) but otherwise would make state leakage possible.

Example fixture:

```
@pytest.fixture(scope='module')
def hooked_transformer() -> HookedTransformer:
    return HookedTransformer(whatever)

Then use in multiple tests like

@pytest.mark.usefixtures("hooked_transformer")
test_x_y_z(hooked_transformer):
```

2. We could address this by defining cleanup methods that are faster than throwing out and re-initialising each object. Example fixture:

```
@pytest.fixture(scope='test')
def hooked_transformer() -> HookedTransformer:
    hooked_transformer = HookedTransformer(whatever)
    yield hooked_transformer
    hooked_transformer.reset()
```

**Comment by mivanit** [comment]
completed in #190
