### ISSUE TITLE
Add Wilson's maze generation algorithm

### ISSUE THREAD

**Issue by luciaquirke** [AISC-understanding-search/maze-transformer#122]
Our mazes are generated using randomised depth first search. This generates mazes with a
[low branching factor and many long corridors](https://en.wikipedia.org/wiki/Maze_generation_algorithm#:~:text=Mazes%20generated%20with%20a%20depth,along%20each%20branch%20before%20backtracking.), because the algorithm explores as far as possible along each branch 
before backtracking.

Wilson's algorithm is an alternative which generates an unbiased sample of mazes from the uniform distribution over all
mazes, using loop-erased random walks. Shifting to mazes generated with this algorithm seems like it would help the 
model learn more generalisable search algorithms because the model would not learn to expect long corridors or other
maze-specific features.

**Comment by valedan** [comment]
FYI the `generate_random_path` function might become slightly confusing once we have new generation algorithms, as described [here](https://github.com/AISC-understanding-search/maze-transformer/pull/102#discussion_r1142995253). We'll need to give some thought to this when implementing.

**Comment by traeuker** [comment]
[Seems done](https://github.com/AISC-understanding-search/maze-transformer/pull/152)
