### ISSUE TITLE
MazeDataset - ensure different representations are always available

### ISSUE THREAD

**Issue by valedan** [AISC-understanding-search/maze-transformer#124]
Currently it's possible to have a dataset where any of `mazes_objs`, `mazes_tokens`, and `mazes_array` are `None`. It would be nice if we could always rely on these representations being present.

I think a nice way to do this would be to choose one of these as the "canonical" representation, and have that be the only version that is actually stored. Then the other representations could be provided by functions that convert from the canonical version as needed. This should help tidy up `__init__` too as right now there is a lot of code in there for converting between these formats.

**Comment by mivanit** [comment]
working on this on the [`zanj-integration-datasets`](https://github.com/AISC-understanding-search/maze-transformer/tree/zanj-integration-datasets) branch (which, misleadingly, contains a rework of the datasets, training loop, and CLI for training).

rough plan:
- [x] integrate with ZANJ for easier saving/loading
- [x] canonical representation of a `MazeDataset` as a list of `SolvedMaze`
- [x] preserve the old interface via cached properties
- [x] seamlessly try to get a dataset from local file, download, or generate on the fly (see `MazeDataset.from_config()` function)
- [ ] pass tests, add new ones
- [ ] change to new interface in example notebooks and tests

**Comment by mivanit** [comment]
resolved in #177
