### ISSUE TITLE
as_pixels() maze visualisation for RCNN comparability

### ISSUE THREAD

**Issue by canrager** [AISC-understanding-search/maze-transformer#133]
This is not immediately urgent, but perhaps we could split `as_ascii()` into an `as_pixels()` function which returns a boolean array of shape `(3, n, n)`. 0th index would be wall/not wall, 1st and 2nd for start/target, respectively. I think this is worth it because we may in the future want to have the ability to feed in a rasterized maze, or see how our transformers compare to RCNNs trained on [similar tasks](https://arxiv.org/abs/2106.04537), which are quite easily interpretable. There might also be clever things to do if our residual stream is an embedding of an image.

the interface of `as_ascii()` would be unchanged, it would just be a relatively simple processing of the results of `as_pixels()`.

However, `as_pixels()` might not be the best name -- any suggestions?

_Originally posted by @mivanit in https://github.com/AISC-understanding-search/maze-transformer/issues/87#issuecomment-1483987666_

**Comment by mivanit** [comment]
actually this has been completed for a while lol
