### ISSUE TITLE
add testing of notebooks in CI

### ISSUE THREAD

**Issue by mivanit** [AISC-understanding-search/maze-transformer#150]
this is being worked on in [add-notebook-testing](https://github.com/AISC-understanding-search/maze-transformer/tree/add-notebook-testing)

# steps:
- [x] [notebook conversion script](https://github.com/AISC-understanding-search/maze-transformer/blob/add-notebook-testing/tests/helpers/convert_ipynb_to_script.py)
- [x] convert and run notebooks from makefile
- [x] disable all plotting in converted notebooks 
  - [x] matplotlib
  - [x] circuitsvis
  - [~] plotly? (this can wait until we actually use plotly somewhere in notebooks)
- [x] add a "default" model to the git repo and/or wandb database (worked on by @luciaquirke )
- [x] add `make test_notebook` to CI
- [x] merge PR :')

# why not `nbconvert`?

(responding to a question by @valedan)

- installing jupyter in CI will add a lot of time -- jupyter does many many things, and even `nbconvert` also includes utilities which we dont need (like converting to PDF)
- actually running `nbconvert` is quite slow! on my machine it was ~2sec per notebook. With just 3 notebooks it might not be a huge deal, but hopefully many notebooks from the experiments repo will eventually migrate here
- the most important reason: even if we use `nbconvert`, we would still have to go into the generated file and modify things to prevent plots from being displayed in CI. The [notebook conversion script](https://github.com/AISC-understanding-search/maze-transformer/blob/add-notebook-testing/tests/helpers/convert_ipynb_to_script.py) would be half as long if it only included processing notebooks, and shorter still if it didn't have code to process all files in a directory (which would just mean it lives in a different file)

**Comment by rusheb** [comment]
FYI there is a tool called nbmake which might do some of this for us.

https://pypi.org/project/nbmake/

**Comment by mivanit** [comment]
> FYI there is a tool called nbmake which might do some of this for us.
> 
> https://pypi.org/project/nbmake/

I don't think there's a way to disable "matplotlib in a widget" for this, so it seems like we'd have to write some kind of script to process it anyway. Thanks for the suggestion though!
