### ISSUE TITLE
Create x,y tokenization scheme

### ISSUE THREAD

**Issue by valedan** [AISC-understanding-search/maze-transformer#164]
Instead of having one token per node, we would instead have a row token and a column token (plus a seperator) representing each node. This would potentially allow us to scale to larger mazes. The problem with node tokens is that when going to larger mazes, the model is dealing with tokens it has never seen before.

Question - What base should the x and y be in? If we use base10, the model would need to be trained on 10x10 mazes before it could generalize. But if we use a base4 scheme, the model would only need to be trained on 4x4 mazes before generalizing.

Blocked by #163

**Comment by mivanit** [comment]
added in #191
see the linked maze-dataset PRs in #191 for more details

the tokenization scheme detailed here is `AOTP_indexed`, but there needs to be more documentation in `maze_dataset` about this.
