### ISSUE TITLE
Facilitate easy division of dataset into training and validation sets

### ISSUE THREAD

**Issue by valedan** [AISC-understanding-search/maze-transformer#173]
We want to make sure we're not evaluating the model on the training set because we're worried about memorization.

**Comment by mivanit** [comment]
the way to do this would be to use the filtering mechanics from #177. specifying a new validation dataset or number of items to sample from the testing dataset is now possible as of #181 by using `TrainConfig.validation_dataset_cfg`

**Comment by traeuker** [comment]
Does that mean this issue gets _closure_? Or do we want to have a better solution for this?

**Comment by mivanit** [comment]
I'm going to mark this as closed for my own peace of mind, it seems to work well enough for now. Happy to re-open if it is unsufficient.
