### ISSUE TITLE
Constrained depth first search

### ISSUE THREAD

**Issue by canrager** [AISC-understanding-search/maze-transformer#183]
Add optional parameters to dataset generation with depth first search:

- [x] `n_connected_nodes` (<= n_nodes)
- [x] `max_tree_depth`
- [x] `generation_origin` coordinate for depth first search

Consider an NxN maze with n_nodes = N^2. The depth first search algorithm should stop after visiting`n_connected_nodes`. This results in islands and smaller mazes. The length of the adjacency list varies with `n_connected_nodes`.`max_tree_depth` constrains the maze to a subarea of NxN. `generation_origin` marks the start coordinate for the depth first search algorithm and gives us the ability to roughly shift the subarea (if max_tree_depth << sqrt(2) * N).

**Comment by mivanit** [comment]
resolved in #184
