### ISSUE TITLE
Create an interactive visualization of model attention over maze positions

### ISSUE THREAD

**Issue by afspies** [AISC-understanding-search/maze-transformer#47]
It would be good to have a visualization akin to the [token-attention visualization ](https://alan-cooney.github.io/CircuitsVis/?path=/docs/tokens-coloredtokensmulti--small-model-example), but with the 2d maze shown instead.

This might make it much easier to understand what different heads are actually doing (as adjacency lists are hard to look at).

**Comment by valedan** [comment]
Did you get a chance to look into this @canrager?

**Comment by afspies** [comment]
I think the easiest way of addressing the second point (whilst also making the plot more aesthetically pleasing) would be to
1. Have the tokens inside of the heatmap (with color black if background light, otherwise white is background dark (I think plotly does this by default with annotated heatmaps)
2. Have the number of columns of the heatmap = the width of the maze, and then just have multiple rows (requires above to work)

**Comment by traeuker** [comment]
Can mentioned it is closed!
