### ISSUE TITLE
`GPTDatasetConfig` missing `grid_n` property?

### ISSUE THREAD

**Issue by afspies** [AISC-understanding-search/maze-transformer#50]
Hi, 

Not sure if the `grid_n` property is a relic of the past, but It seems the to still be stored in the `dataset_cfg` of `ConfigHolder`, though it is not specified as a property of `GPTDatasetConfig` unless I am mistaken.

**Comment by valedan** [comment]
Hey @afspies, I just took a quick look and `grid_n` is a property on `MazeDatasetConfig`, which as you point out is generally the config type used for `dataset_cfg`. 

Are there any concerns with how this is working currently?
