### ISSUE TITLE
Use shared model and dataset for all integration tests

### ISSUE THREAD

**Issue by afspies** [AISC-understanding-search/maze-transformer#70]
There is some duplication between here and `test_train_model.py`. This increases the test run duration with quite low benefit. 

I think we could solve this in one of 2 ways:
- Combine them into a single test
- Create some test data which is used as the starting point for this test (i.e. this test would start after the point we have a trained model)

Thoughts?

_Originally posted by @rusheb in https://github.com/AISC-understanding-search/maze-transformer/pull/48#discussion_r1127862490_

**Comment by valedan** [comment]
I had the same thought when working on tests recently - we're wasting a lot of time creating datasets and training models in integration tests!

I think it would be nice to have some preset test data and test model that we can use in tests. 

The only question is where to store them? I think if they're fairly small it's fine to just store them in git.

**Comment by rusheb** [comment]
Yes, I think we should store them in git and move them if it becomes a problem

**Comment by valedan** [comment]
Assigning myself because I've spent a lot of time today staring at slow tests and thinking of ways to speed them up. Probably won't get to it until next week.

**Comment by mivanit** [comment]
fixed in #190
