### ISSUE TITLE
WARNING: code hash mismatch for maze_ctor gen_dfs

### ISSUE THREAD

**Issue by rusheb** [AISC-understanding-search/maze-transformer#83]
We see this warning a lot when running notebooks. Would be good to get to the bottom of why it happens and get rid of it.

**Comment by rusheb** [comment]
Seems related to the `maze_ctor` field on the `dataset_cfg`:

```python
 "dataset_cfg": {
    ...,
    "maze_ctor": {
        "__name__": "gen_dfs",
        "code_hash": 8257923402625479000,
        "sourcefile": "/Users/rusheb/code/maze-transformer/maze_transformer/generation/generators.py"
    },
    ...
}

**Comment by valedan** [comment]
@rusheb Any idea what the priority is here?

**Comment by mivanit** [comment]
this was related to hashes not being stable across runs. fixed through usage of [`muutils.misc.stable_hash`](https://github.com/mivanit/muutils/blob/main/muutils/misc.py#L5)
