### ISSUE TITLE
alternate version of as_img() with thin walls and no connection squares

### ISSUE THREAD

**Issue by rusheb** [AISC-understanding-search/maze-transformer#84]
I find it a bit confusing to look at the image and have connections represented as white squares that look identical to nodes. It seems like it would make more sense to not render connections. I assume the reason we're doing that is because the walls (non-connections) take up a full square. I wonder if an alternate version of `as_img()` with thin walls and no connection squares would be clearer... 🤔

_Originally posted by @valedan in https://github.com/AISC-understanding-search/maze-transformer/pull/78#discussion_r1133899968_

**Comment by afspies** [comment]
Could be a reasonable first issue for people trying to get familiar with maze representation

**Comment by canrager** [comment]
I'll take a look
