### ISSUE TITLE
Guarantee that entire adjacency list is present during training

### ISSUE THREAD

**Issue by luciaquirke** [AISC-understanding-search/maze-transformer#89]
Apparently in some part of the training code we are truncating the training sequence. Removing that should be sufficient to resolve this. 

Acceptance criteria:
* Unit test that verifies new behaviour

**Comment by valedan** [comment]
Based on the research meeting yesterday it sounds like this isn't actually an issue. @mivanit was there anything else to do on this ticket?

**Comment by mivanit** [comment]
I think a unit test verifying the behavior would be good, other than that I think we are fine.
