### ISSUE TITLE
workflow for adjusting training parameters makes experimentation difficult

### ISSUE THREAD

**Issue by rusheb** [AISC-understanding-search/maze-transformer#98]
it is difficult to train different models because of the steps required to update configs. this involves editing the configs in `config.py` by modifying or adding items to `_GPT_CONFIGS_LIST` or `_TRAINING_CONFIGS_LIST`. changing python files affects version control which adds further inconvenience

Not sure on the best way to fix this. Some options:
- setting training parameters from the command line. Though, there may be so many parameters that also makes this inconvenient
- use notebooks?
- can we use wandb to make this easier? e.g. by leveraging artifacts?
- config management libraries e.g. hydra? 

Requires more research

**Comment by mivanit** [comment]
I think this is mostly resolved via #177 and the ability to modify config params via CLI
